---
  name : General Config

  hosts:  routers
  task:

    - name: Add Banner

      ios_banner:


      banner:login
      text: |
      Nicolas Cage is the Tiger King
      state: present 


    - name: Merge provided configuration with device configuration
      ios_interfaces:
      config:
      - name:GigabitEthernet2
        description: Configured and Merged by Ansible Network
      enable: true
